// Constantes de acciones para el reducer de SCAT
export const ACTIONS = {
  SET_PROJECT_DATA: 'SET_PROJECT_DATA',
  SET_EVALUACION_DATA: 'SET_EVALUACION_DATA',
  SET_CONTACTO_DATA: 'SET_CONTACTO_DATA',
  SET_CAUSAS_INMEDIATAS_DATA: 'SET_CAUSAS_INMEDIATAS_DATA',
  SET_CAUSAS_BASICAS_DATA: 'SET_CAUSAS_BASICAS_DATA',
  SET_NECESIDADES_CONTROL_DATA: 'SET_NECESIDADES_CONTROL_DATA',
  SET_EDITING_STATE: 'SET_EDITING_STATE',
  LOAD_DATA: 'LOAD_DATA',
  RESET_DATA: 'RESET_DATA',
  CLEAR_EDITING_DATA: 'CLEAR_EDITING_DATA'
};